# Generated by Django 5.0 on 2023-12-26 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("Customer_ID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=255)),
                ("Address", models.CharField(max_length=255)),
                ("Phone_number", models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("Product_ID", models.AutoField(primary_key=True, serialize=False)),
                ("Product_Name", models.CharField(max_length=255)),
                ("Price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("Quantity", models.PositiveIntegerField()),
                ("Tax", models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("Invoice_ID", models.AutoField(primary_key=True, serialize=False)),
                ("Date", models.DateField()),
                ("Payment_method", models.CharField(max_length=50)),
                (
                    "Customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Invoice.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Quantity", models.PositiveIntegerField()),
                (
                    "Invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Invoice.invoice",
                    ),
                ),
                (
                    "Product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Invoice.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="invoice",
            name="Products",
            field=models.ManyToManyField(
                through="Invoice.InvoiceItem", to="Invoice.product"
            ),
        ),
    ]
