# Generated by Django 5.0 on 2023-12-26 10:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Invoice", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="Address",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="Phone_number",
        ),
    ]
